In [2]:
import numpy as np
a=np.array([1,6,3,4,5,6,7,8,9])
x=np.where(a==7)
y=np.where(a==6)
print(x)
print(y)

(array([6]),)
(array([1, 5]),)


In [3]:
import numpy as np
a=np.array([1,2,3,4])
x=np.where(a==7)
print(x)

(array([], dtype=int64),)


In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(a%2==0)
y=np.where(a%3==1)
print(x)
print(y)

(array([1, 3, 5, 7, 9]),)
(array([0, 3, 6, 9]),)


In [7]:
import numpy as np
a=np.array([1,2,3,5,6])
x=np.searchsorted(a,5,side='left')
y=np.searchsorted(a,5,side='right')
print("left pos:",x)
print('right pos:',y)

left pos: 3
right pos: 4


In [8]:
import numpy as np
a=np.array([5,7,8,2,3,1])
print(np.sort(a))
b=np.array([[1,3,8],[2,1,7]])
print(np.sort(b))

[1 2 3 5 7 8]
[[1 3 8]
 [1 2 7]]


In [11]:
import numpy as np
a=np.array([31,78,69,88])
x=[True,True,True,True]
new=a[x]
print(x)
print(new)

[True, True, True, True]
[31 78 69 88]


In [13]:
import numpy as np
a=np.array([31,78,69,88])
filter_a=a>70
new=a[filter_a]
print(filter_a)
print(new)

[False  True False  True]
[78 88]
