In [1]:
import numpy as np
a= np.array([10,20,30,40])
slice1=a[1:2]
print(slice1)

[20]


In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice2=a[0:10:2]
print(slice2)

[1 3 5 7 9]


In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice3=a[::3]
print(slice3)

[1 4 7]


In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice4=a[::-1]
print(slice4)

[9 8 7 6 5 4 3 2 1]


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=a[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=a[:2,:1]
print(subarray)

[[1]
 [4]]


In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
col1=a[:,0]
print(col1)

[1 4 7]


In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
row2=a[0,:]
print(row2)

[1 2 3]


In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
row2=a[0:2:1]
print(row2)

[[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np
import array
a=array.array('i',[1,2,3,4,5])
print(a[0])
print(a[3])

1
4


In [14]:
import numpy as np
import array
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(a[0,0])
print(a[2,1])

1
7


In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print("basic indexing:",a[1])
print("negative indexing:",a[-1])
print("slicing indexing:",a[1:4])
print("Boolean indexing:",a[a>0])
print("fancy indexing:",a[[1,3]])

basic indexing: 2
negative indexing: 5
slicing indexing: [2 3 4]
Boolean indexing: [1 2 3 4 5]
fancy indexing: [2 4]


In [4]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result= np.hstack((arr1,arr2))
print("horizontal join:\n",result)

horizontal join:
 [[1 2 5 6]
 [3 4 7 8]]


In [5]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result= np.vstack((arr1,arr2))
print("vertical join:\n",result)

vertical join:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result= np.dstack((arr1,arr2))
print("Depth join:\n",result)

Depth join:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [8]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
result=np.split(arr,3)
print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [9]:
import numpy as np
arr=np.array([10,20,30,40,50])
result=np.array_split(arr,3)
print(result)

[array([10, 20]), array([30, 40]), array([50])]
