In [1]:
import numpy as np
a=np.array([1,2,3])
print("one dimensional array:",a)

one dimensional array: [1 2 3]


In [2]:
import numpy as np
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("three dimensional array:",c)

three dimensional array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import numpy as np
c=np.array([[1,2,3],[4,5,6]])
print("two dimensional array:",c)

two dimensional array: [[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:

import numpy as np
c=np.random.random((3,2))
print("\n Array with all random values:\n",c)


 Array with all random values:
 [[0.11020522 0.85608357]
 [0.53487301 0.61860064]
 [0.09479699 0.52250838]]


In [8]:
import numpy as np
c=np.random.random((3,2))
new=c.reshape((2,3))
print("\n original array:\n",c)
print("\n new array:\n",new)


 original array:
 [[0.07871069 0.4357635 ]
 [0.73904882 0.87810039]
 [0.64047278 0.94264255]]

 new array:
 [[0.07871069 0.4357635  0.73904882]
 [0.87810039 0.64047278 0.94264255]]


In [9]:
import numpy as np
c=np.arange(10,100,10)
print("\n sequence array:\n",c)


 sequence array:
 [10 20 30 40 50 60 70 80 90]


In [13]:
import numpy as np
a=np.random.random((3,2))
c=a.flatten()
print("\n original array:\n",a)
print('\n flattened array:\n',c)
print("\n dimension of the array:\n",a.ndim)



 original array:
 [[0.77695839 0.11213724]
 [0.15827749 0.44355524]
 [0.12823022 0.03354346]]

 flattened array:
 [0.77695839 0.11213724 0.15827749 0.44355524 0.12823022 0.03354346]

 dimension of the array:
 2


In [14]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('\n original array:\n',a)
print('\n dimension of the array:\n',a.ndim)


 original array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

 dimension of the array:
 3


In [16]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("shape of array",a.shape)

shape of array (3, 3)


In [17]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('data type',a.dtype)

data type int64


In [2]:
import numpy as np
a=[10,20,30]
a=np.array(a)
new=a.astype('float64')
print(new)

[10. 20. 30.]
