In [4]:
import numpy as np
a=np.random.random((3,4))
print(' array with random value: \n',a)

 array with random value: 
 [[0.26944377 0.76107127 0.77398373 0.32648999]
 [0.43644405 0.89799426 0.25572137 0.85804485]
 [0.68389153 0.93894507 0.3553355  0.69371329]]


In [5]:
import numpy as np
a=np.zeros((3,4))
print('array with zeros:\n',a)

array with zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
import numpy as np
a=np.arange(5,30,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [10]:
import numpy as np
a=np.random.random((3,4))
print('\nshape:\n',a.shape)
print('\nDimension: \n',a.ndim)
print("\n Datatype:\n",a.dtype)
print("\n flatten: \n",a.flatten())


shape:
 (3, 4)

Dimension: 
 2

 Datatype:
 float64

 flatten: 
 [0.92095113 0.13697355 0.42507131 0.74266301 0.77767167 0.09333686
 0.47166307 0.17048143 0.07910098 0.33121583 0.29672321 0.17199066]
